---
# tasks file for ansible-role-samba
- name: debug variable test
  debug:
    var: samba_admin_password

- name: install packages required for samba
  apt:
    name:
        - samba
        - winbind
        - libnss-winbind
        - libpam-winbind
        - krb5-user
    update_cache: yes

- name: check if domain exists
  stat:
    path: /var/log/.samba_domain_provisioned
  register: result_check_samba_domain_exists

- name: debug result check if domain exists
  debug:
    var: result_check_samba_domain_exists

- name: create backup of original samba configuration file /etc/samba/smb.conf
  command: mv /etc/samba/smb.conf /etc/samba/smb.conf.original
  when: >
    not result_check_samba_domain_exists['stat']['exists']
    or (samba_force_domain_creation is defined
        and samba_force_domain_creation)

- name: create backup of original kerberos configuration file /etc/krb5.conf
  command: mv /etc/krb5.conf /etc/krb5.conf.original
  when: >
    not result_check_samba_domain_exists['stat']['exists']
    or (samba_force_domain_creation is defined
        and samba_force_domain_creation)

- name: create samba ad domain
  shell: >
    samba-tool domain provision --use-rfc2307
    --realm={{ samba_realm|upper }}
    --domain={{ samba_domain|default(samba_realm.split(".")[0], true)|upper }}
    --adminpass={{ samba_admin_password }}
    --server-role=dc
  when: >
    not result_check_samba_domain_exists['stat']['exists']
    or (samba_force_domain_creation is defined
        and samba_force_domain_creation)
  register: result_samba_domain_creation

- name: debug result create samba ad domain
  debug:
    var: result_samba_domain_creation

- name: install new kerberos config file created by samba-tool
  command: cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
  when: >
    result_samba_domain_creation['changed']

- name: mark domain as created
  file:
    dest: /var/log/.samba_domain_provisioned
    state: touch
  when: >
    result_samba_domain_creation['changed']

- name: ensure dns forwarder is not present in /etc/samba/smb.conf
  lineinfile:
    dest: /etc/samba/smb.conf
    regexp: '\s*dns forwarder = '
    state: absent

- name: archive existing /etc/resolv.conf
  template:
      src: etc/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
  notify:
    - restart samba-ad-dc
